version: '3'
services:
  backend:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/web/app
    env_file: 
      - ./env/dev/backend.env
      - ./env/dev/db.env
    networks:
      - database_network
    command: "/web/app/start_django.sh"
    ports:
      - '8000:8000'
    depends_on:
      - database

  database:
    restart: always
    image: postgres:12
    ports:
      - "5555:5432"
    env_file: 
      - ./env/dev/db.env
    volumes:
      - database_data:/var/lib/postgresql/data/
    networks:
      - database_network
 
networks: 
  database_network:
    driver: bridge

volumes:
  database_data:  # <-- declare the database volume 
